

### login
GET http://localhost:3003/api/login

###
POST http://localhost:3003/api/login  HTTP/1.1
Content-Type:application/json

{
    "username": "mluukkai",
    "password": "salainen"
}

### Blogs
GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs  HTTP/1.1
Content-Type:application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2MjA0MGMwYmMwMGE1ZDJmMWY2OGE5ZGYiLCJpYXQiOjE2NDQ1MTgxMjJ9.bhiyBWYU0k0QlQD7YR2c9y7RqIqdFLA_I0gVMOw-i2c

{
    "title": "test's Notions",
    "author": "Nathan Watkins",
    "url": "https://nathansnotions.com",
    "likes": 69
}


###
DELETE http://localhost:3003/api/blogs/62054568c15a9372b8e63391  HTTP/1.1
Content-Type:application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2MjA0MGMwYmMwMGE1ZDJmMWY2OGE5ZGYiLCJpYXQiOjE2NDQ0NTI0Nzl9.QXGOpxdJW8srKZm_44x6oJ2JHVnHidzQI-C7IQPV3tQ



### Users
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users  HTTP/1.1
Content-Type:application/json


{
    "username": "mluukkai",
    "name": "Matti Luukkainen",
    "password": "salainen"
}

# {
#     "blogs": [],
#     "username": "root",
#     "name": "Matti Luukkainen",
#     "password": "salainen"
# }

